version: '3'

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    ports:
      - '80:80'
      - '443:443'
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    networks:
      - caddy
    dns:
      - 1.1.1.1
    environment:
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=${QBT_WEBUI_PORT}
      - TZ=${TZ}
    volumes:
      - ./appdata/config:/config
      - /stuff:/downloads
    ports:
      - 49174:49174
      - 49174:49174/udp
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    networks:
      - caddy
    restart: always

  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${PIHOLE_WEB_PASSWORD}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    ports:
      - 53:53/udp
    networks:
      - caddy
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: always

networks:
  caddy:
    driver: bridge
